/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

const FILE_IS_TOO_BIG = 'FILE_IS_TOO_BIG';
const NOT_ENOUGH_STORAGE = 'NOT_ENOUGH_STORAGE';
const EMPTY_TRASH = 'EMPTY_TRASH';
const SOURCE_CARD_NOT_COPYABLE = 'SOURCE_CARD_NOT_COPYABLE';
const SOURCE_CARD_NOT_MOVABLE = 'SOURCE_CARD_NOT_MOVABLE';
const LEVEL_UP = 'LEVEL_UP';
const BADGE_UNLOCKED = 'BADGE_UNLOCKED';
const XP_GAINED = 'XP_GAINED';

export default {
  FILE_IS_TOO_BIG,
  NOT_ENOUGH_STORAGE,
  EMPTY_TRASH,
  SOURCE_CARD_NOT_COPYABLE,
  SOURCE_CARD_NOT_MOVABLE,
  LEVEL_UP,
  BADGE_UNLOCKED,
  XP_GAINED,
};
